In [80]:
# imports
import sys
import os
import os
from dotenv import load_dotenv

# getting current state of path:
print("current sys path:", sys.path)

# getting the repo path:
repo_path = os.path.abspath(os.path.join(os.getcwd(), ".."))
print("path to this repo: ", repo_path)
# adding the repo path to the sys path:
if repo_path not in sys.path:
    sys.path.append(repo_path)
print(sys.path)

current sys path: ['/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python313.zip', '/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python3.13', '/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python3.13/lib-dynload', '', '/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python3.13/site-packages', '/mnt/c/dev/etl_pipeline']
path to this repo:  /mnt/c/dev/etl_pipeline
['/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python313.zip', '/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python3.13', '/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python3.13/lib-dynload', '', '/home/andre875/anaconda3/envs/etl_pipeline_dev/lib/python3.13/site-packages', '/mnt/c/dev/etl_pipeline']

In [160]:
import importlib
import src.db_handler
importlib.reload(src.db_handler)
from src.db_handler import DatabaseHandler

# Confirming the class can get initialized well

In [161]:
# Load environment variables from .env file
load_dotenv()

# Get username and password from environment variables
username = os.getenv('DB_USERNAME')
password = os.getenv('DB_PASSWORD')

# Create an instance of DatabaseHandler
db_handler = DatabaseHandler(f'postgresql://{username}:{password}@localhost:5432/field_mrv')

/mnt/c/dev/etl_pipeline/src/db_handler.py:26: SAWarning: Did not recognize type 'geometry' of column 'shape'
  self.metadata: MetaData = MetaData()
/mnt/c/dev/etl_pipeline/src/db_handler.py:26: SAWarning: Did not recognize type 'geometry' of column 'location'
  self.metadata: MetaData = MetaData()
/mnt/c/dev/etl_pipeline/src/db_handler.py:26: SAWarning: Did not recognize type 'geometry' of column 'service_area'
  self.metadata: MetaData = MetaData()

# information methods

In [162]:
# Example usage
print(db_handler.get_table_names())

['spatial_ref_sys', 'locations', 'field_boundaries']

In [163]:
# Get the column names of the 'locations' table
columns_loc = db_handler.get_column_info_dataframe('locations')
columns_loc.head().T

                   0             1         2             3
name              id          name  location  service_area
type         INTEGER  VARCHAR(100)      NULL          NULL
nullable       False          True      True          True
default         None          None      None          None
primary_key     True         False     False         False
foreign_key       {}            {}        {}            {}
unique          None          None      None          None

In [164]:
# Get the column names of the 'locations' table
columns = db_handler.get_column_info_dataframe('field_boundaries')
columns.head().T

,0,1,2,3,4
name,boundary_id,location_id,shape,area_hectares,crop_type
type,INTEGER,INTEGER,NULL,DOUBLE PRECISION,VARCHAR(100)
nullable,False,True,True,True,True
default,None,None,None,None,None
primary_key,True,False,False,False,False
foreign_key,{},"{ForeignKey('locations.id'), ForeignKey('locat...",{},{},{}
unique,None,None,None,None,None

# Reading the data in

In [165]:
location_table = db_handler.get_table_data('locations')
display(location_table)

,id,name,location,service_area
0,2,Fazenda Boa Vista,0101000020E6100000F437A11001F747C00113B875378F...,0103000020E61000000100000005000000D5B2B5BE48F8...

In [166]:
field_boundaries = db_handler.get_table_data('field_boundaries')
display(field_boundaries)

,boundary_id,location_id,shape,area_hectares,crop_type,last_surveyed,soil_type,elevation_avg,created_at,updated_at
0,3,2,0103000020E610000001000000050000000E677E3507F8...,25.7,Coffee,2025-01-03 13:21:51.208420,None,None,2025-03-03 13:21:51.208420,2025-03-03 13:21:51.208420
1,4,2,0103000020E610000001000000050000004A46CEC29EF6...,18.3,Sugarcane,2025-02-03 13:22:00.842088,None,None,2025-03-03 13:22:00.842088,2025-03-03 13:22:00.842088

# reading in the data to geopandas

In [ ]:
# Create an instance of DatabaseHandler
db_handler = DatabaseHandler(f'postgresql://{username}:{password}@localhost:5432/field_mrv')
location_table = db_handler.execute_geo_sql("Select id, name, service_area, location as geom from locations")
print(type(location_table))
location_table.head()

In [ ]:
field_boundary_table = db_handler.execute_geo_sql("""
    Select 
    boundary_id, 
    location_id,
    shape,
    area_hectares,
    crop_type,
    last_surveyed,
    soil_type,
    elevation_avg as geom 
    from field_boundaries 
    """)
print(type(field_boundary_table))
field_boundary_table.head()

# Joining the two tables together:

In [ ]:
# Joining the location_table and field_boundary_table on the location_id column
joined_table = location_table.merge(field_boundary_table, left_on='id', right_on='location_id')
print(type(joined_table))
print(joined_table.info())
joined_table.head()

In [144]:

# Close the connection
db_handler.close_connection()